2019-06-28 09:51:21,434 - root - ERROR - utils  - 153 - JD(27115314210)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:51:21,435 - root - ERROR - utils  - 153 - JD(27115314210)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:51:41,949 - root - ERROR - utils  - 153 - JD(8031600)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:51:41,949 - root - ERROR - utils  - 153 - JD(8031600)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
