2019-06-28 09:45:22,513 - root - ERROR - utils  - 153 - JD(27115314210)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:45:22,514 - root - ERROR - utils  - 153 - JD(27115314210)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:45:41,729 - root - ERROR - utils  - 153 - JD(8031600)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:45:41,731 - root - ERROR - utils  - 153 - JD(8031600)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:46:00,421 - root - ERROR - utils  - 153 - JD(100001470134)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:46:00,421 - root - ERROR - utils  - 153 - JD(100001470134)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:46:07,756 - root - ERROR - utils  - 153 - JD(100001470134)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:46:07,756 - root - ERROR - utils  - 153 - JD(100001470134)报错信息：评论列表获取失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 40, in getComment
    commentSummary = comm_dict['comments']  # 得到包含评论的字典组成的列表
KeyError: 'comments'
2019-06-28 09:46:21,031 - root - ERROR - utils  - 153 - JD(34326476497)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:46:21,032 - root - ERROR - utils  - 153 - JD(34326476497)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:46:39,448 - root - ERROR - utils  - 153 - JD(100001667527)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:46:39,450 - root - ERROR - utils  - 153 - JD(100001667527)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:46:59,835 - root - ERROR - utils  - 153 - JD(7224868)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:46:59,837 - root - ERROR - utils  - 153 - JD(7224868)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
